MAP = {
    "main" : [
        "========================================",
        "     [main.changeLang] : [langHere]",
        "",
        "              [title.main]",
        "  ↑",
        " ←↓→ [key.move]   |Enter| [key.enter]    |ESC| [key.esc]",
        "",
        "",
        "    [main.create]     [main.search]    [main.list]",
        "",
        "",
        "========================================",
        "[main.help]",
    ],

    "create" : [
        "========================================",
        "",
        "              [title.create]",
        "",
        "[create.title] : [titleHere]",
        "",
        "[create.tag] : [tagHere]",
        "",
        "",
        "[create.content] : [contentHere]",
        "",
        "",
        "[create.create]",
        "",
        "========================================",
        "[create.help]"
    ],

	"list" : [
        "========================================",
        "",
        "              [title.list] - [list.countHere][list.count]",
        "[list.previous]",
        "[list.item0]",
        "[list.item1]",
        "[list.item2]",
        "[list.item3]",
        "[list.item4]",
        "[list.item5]",
        "[list.item6]",
        "[list.item7]",
        "[list.item8]",
        "[list.next]",
        "========================================",
        "[list.help]"
    ],

	"show" : [
        "========================================",
        "",
        "              [title.show]",
        "",
        "[create.title] : [titleHere]",
        "",
        "[create.tag] : [tagHere]",
        "",
        "",
        "[create.content] : [contentHere]",
        "",
        "",
        "[create.time] : [timeHere]",
        "",
        "========================================",
        "[show.help]"
    ],

	"search" : [
        "========================================",
        "",
        "              [title.search] - [search.countHere][search.count]",
        "",
        "[search.sort] : [search.sort.time] [search.sort.title] [search.sort.tag] [search.sort.content]",
        "[search.text] : [searchHere]",
        "",
        "[list.previous]",
        "[list.item0]",
        "[list.item1]",
        "[list.item2]",
        "[list.item3]",
        "[list.item4]",
        "[list.next]",
        "========================================",
        "[create.help]"
    ],
}